# Generated by Django 3.2.7 on 2021-09-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Preco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=200)),
                ('class_indicativa', models.IntegerField()),
                ('total_estoque', models.IntegerField()),
                ('total_disponivel', models.IntegerField()),
                ('max_dias', models.IntegerField()),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cat_preco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora_admin.cat_preco')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora_admin.genero')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora_admin.midia')),
            ],
        ),
    ]
