# Generated by Django 3.2.7 on 2021-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_admin', '0002_cat_preco_inventario_midia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('fator_multa', models.IntegerField()),
                ('pontos_fidelidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('isadmin', models.BooleanField()),
                ('login', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
    ]
