# Generated by Django 3.2.7 on 2021-09-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locadora_admin', '0003_clientes_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateField()),
                ('data_prev_fechamento', models.DateField()),
                ('data_fechamento', models.DateField(null=True)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('observacoes', models.CharField(max_length=300, null=True)),
                ('pago', models.BooleanField()),
                ('compra', models.BooleanField()),
                ('status', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora_admin.clientes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itens_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora_admin.inventario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locadora_admin.pedidos')),
            ],
        ),
    ]
