# Generated by Django 3.2.7 on 2022-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_admin', '0005_remove_pedidos_valor_previsto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
