# Generated by Django 3.2.7 on 2022-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_admin', '0006_pedidos_valor_previsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
