# Generated by Django 3.2.7 on 2022-11-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_admin', '0007_alter_pedidos_valor_previsto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='valor_previsto',
        ),
    ]
