# Generated by Django 3.2.7 on 2022-11-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_admin', '0009_pedidos_valor_previsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora_admin.pedidos'),
        ),
    ]
